import React from 'react'

const HomePage = () => {
  return (
    <div className="bg-base text-dark">


      {/* HERO */}
      <section className="grid grid-cols-2 gap-10 px-20 py-20">
        <div>
          <span className="border border-primary text-primary px-4 py-1 rounded-full text-sm">
            AI-Powered Meeting Documentation
          </span>

          <h1 className="text-5xl font-semibold mt-6 leading-tight">
            Turn Meetings into <br />
            <span className="text-primary">Clear, Actionable Notes</span>
          </h1>

          <p className="text-muted mt-6 max-w-md">
            MeeTscribe transcribes meetings, summarizes discussions, and generates
            professional documentation automatically.
          </p>

          <div className="mt-8 flex gap-4">
            <button className="bg-primary text-white px-6 py-3 rounded-lg">
              Get Started Free
            </button>
            <button className="border border-primary text-primary px-6 py-3 rounded-lg">
              View Demo
            </button>
          </div>
        </div>

        {/* MOCK DASHBOARD */}
        <div className="bg-white rounded-2xl shadow-lg p-6">
          <h3 className="font-medium mb-4">Live Transcript</h3>
          <div className="space-y-3 text-sm text-muted">
            <p>• Speaker 1: Project discussion started...</p>
            <p>• Speaker 2: Timeline needs adjustment...</p>
            <p>• Speaker 3: Action items assigned...</p>
          </div>

          <div className="mt-6 grid grid-cols-2 gap-4">
            <div className="border border-border rounded-lg p-3">
              <h4 className="font-medium">Key Summary</h4>
              <p className="text-sm text-muted mt-2">
                Main goals and decisions highlighted.
              </p>
            </div>
            <div className="border border-border rounded-lg p-3">
              <h4 className="font-medium">Action Items</h4>
              <p className="text-sm text-muted mt-2">
                Tasks auto-generated by AI.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* PROBLEMS */}
      <section className="bg-[#F5F5F4] px-20 py-12 grid grid-cols-3 gap-6">
        {[
          "Manual note-taking is slow",
          "Important points get missed",
          "Documentation takes hours",
        ].map((text, i) => (
          <div key={i} className="bg-white p-6 rounded-xl shadow-sm">
            <p className="font-medium">{text}</p>
          </div>
        ))}
      </section>

      {/* FEATURES */}
      <section className="px-20 py-20">
        <h2 className="text-3xl font-semibold text-center mb-12">
          Key Features
        </h2>

        <div className="grid grid-cols-3 gap-8">
          {[
            "Live Transcription",
            "Smart Summaries",
            "Auto Documentation",
            "Multi-Language Support",
            "Cloud Storage",
            "Secure & Private",
          ].map((feature, i) => (
            <div
              key={i}
              className="bg-white border border-border rounded-xl p-6 hover:border-primary transition"
            >
              <h3 className="font-medium">{feature}</h3>
              <p className="text-sm text-muted mt-2">
                AI-powered feature to improve productivity.
              </p>
            </div>
          ))}
        </div>
      </section>

      {/* HOW IT WORKS */}
      <section className="px-20 py-16 text-center">
        <h2 className="text-3xl font-semibold mb-10">How It Works</h2>
        <div className="flex justify-center gap-10">
          {["Record", "AI Transcribes", "Get Summary", "Download"].map(
            (step, i) => (
              <div key={i}>
                <div className="bg-primary text-white w-10 h-10 rounded-full flex items-center justify-center mx-auto">
                  {i + 1}
                </div>
                <p className="mt-3">{step}</p>
              </div>
            )
          )}
        </div>
      </section>

      {/* CTA */}
      <section className="bg-primary text-white px-20 py-16 text-center">
        <h2 className="text-3xl font-semibold">
          Start documenting your meetings the smart way
        </h2>
        <button className="mt-6 bg-white text-dark px-6 py-3 rounded-lg">
          Get Started Free
        </button>
      </section>

      {/* FOOTER */}
      <footer className="bg-dark text-gray-300 px-20 py-10 grid grid-cols-4 gap-8">
        <div>
          <h3 className="text-white font-semibold">MeeTscribe</h3>
          <p className="text-sm mt-2">
            AI-powered meeting transcription & documentation.
          </p>
        </div>
        <div>
          <h4 className="text-white">Links</h4>
          <p className="mt-2">Features</p>
          <p>Use Cases</p>
        </div>
        <div>
          <h4 className="text-white">GitHub</h4>
          <p className="mt-2">Project Repository</p>
        </div>
        <div>
          <h4 className="text-white">Contact</h4>
          <p className="mt-2">meetscribe@email.com</p>
        </div>
      </footer>

    </div>
  );
};

  


export default HomePage;